[tool.black]
target-version = ['py311']

[tool.mypy]
python_version = "3.11"
mypy_path = ["${MYPY_CONFIG_FILE_DIR}/scripts"]

[[tool.mypy.overrides]]
module = [
    "boto3.*",
    "gooddata_api_client.*",
    "gooddata_sdk.*",
    "pytest.*",
    "yaml.*",
    "jmespath.*",
    "moto.*",
    "gooddata_api_client.*",
    "requests.*",
]
ignore_missing_imports = true
check_untyped_defs = true


[tool.ruff]
line-length = 88
